name: Compile Resume PDF

on:
    push:
      branches:
        - main
      tags:
        - 'v*'
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Build PDF
      run: make
    
    - name: Check build output
      run: |
        if [ -z "$(find dist/ -name '*.pdf')" ]; then
          echo "Build failed: No PDF found in dist directory"
          exit 1
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*