name: Compile Resume PDF and create release, if tagged

on: 
    push: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Build binary
      run: |
        chmod +x build.sh
        ./build.sh
    
    - name: Check build output
      run: |
        if [ -z "$(find dest -name '*.pdf')" ]; then
          echo "Build failed: No PDF found in dest directory"
          exit 1
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dest/*